export const PERMISSIONS = {
  DEPARTMENTS_READ: "departments:read",
  DEPARTMENTS_WRITE: "departments:write",
  DEPARTMENTS_DELETE: "departments:delete",
  TEAMS_READ: "teams:read",
  TEAMS_WRITE: "teams:write",
  TEAMS_DELETE: "teams:delete",
  USERS_READ: "users:read",
  USERS_WRITE: "users:write",
  USERS_ASSIGN_ROLE: "users:assign-role",
  ROLES_READ: "roles:read",
  ROLES_WRITE: "roles:write",
  ROLES_DELETE: "roles:delete",
  PERMISSIONS_READ: "permissions:read",
  PERMISSIONS_WRITE: "permissions:write",
  PERMISSIONS_DELETE: "permissions:delete",
  PERMISSIONS_ASSIGN: "permissions:assign",
  DOCUMENTS_READ: "documents:read",
  DOCUMENTS_WRITE: "documents:write",
  DOCUMENTS_DELETE: "documents:delete",
  KNOWLEDGE_QUERY: "knowledge:query",
  EMPLOYEES_READ: "employees:read",
  EMPLOYEES_WRITE: "employees:write",
  EMPLOYEES_DELETE: "employees:delete",
  EMPLOYEES_CHAT: "employees:chat",
  AGENT_TEAMS_READ: "agent_teams:read",
  AGENT_TEAMS_WRITE: "agent_teams:write",
  AGENT_TEAMS_DELETE: "agent_teams:delete",
  AGENT_TEAMS_EXECUTE: "agent_teams:execute",
  WORKFLOWS_READ: "workflows:read",
  WORKFLOWS_WRITE: "workflows:write",
  WORKFLOWS_DELETE: "workflows:delete",
  RESEARCH_PROJECTS_READ: "research_projects:read",
  RESEARCH_PROJECTS_WRITE: "research_projects:write",
  RESEARCH_PROJECTS_EXECUTE: "research_projects:execute",
  RESEARCH_PROJECTS_DELETE: "research_projects:delete",
  BROWSER_PROFILES_READ: "browser_profiles:read",
  BROWSER_PROFILES_WRITE: "browser_profiles:write",
  BROWSER_PROFILES_DELETE: "browser_profiles:delete",
  BROWSER_TASKS_READ: "browser_tasks:read",
  BROWSER_TASKS_WRITE: "browser_tasks:write",
  BROWSER_TASKS_DELETE: "browser_tasks:delete",
  BROWSER_TASKS_EXECUTE: "browser_tasks:execute",
} as const;

export function hasPermission(
  permissions: string[] | undefined,
  slug: string,
): boolean {
  return permissions?.includes(slug) ?? false;
}
