from fastapi import APIRouter

from app.api.v1.endpoints import (
    agent_tasks,
    agent_teams,
    auth,
    browser_profiles,
    browser_tasks,
    conversations,
    dashboard,
    departments,
    documents,
    employees,
    health,
    knowledge,
    omnichannel_channels,
    omnichannel_conversations,
    omnichannel_realtime,
    omnichannel_webhooks,
    omnichannel_widget,
    organizations,
    permissions,
    research_projects,
    roles,
    support_categories,
    support_tickets,
    teams,
    users,
    voice_agents,
    voice_sessions,
    workflows,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(organizations.router)
api_router.include_router(dashboard.router)
api_router.include_router(documents.router)
api_router.include_router(knowledge.router)
api_router.include_router(employees.router)
api_router.include_router(agent_teams.router)
api_router.include_router(agent_tasks.router)
api_router.include_router(workflows.router)
api_router.include_router(research_projects.router)
api_router.include_router(browser_profiles.router)
api_router.include_router(browser_tasks.router)
api_router.include_router(support_categories.router)
api_router.include_router(support_tickets.router)
api_router.include_router(voice_agents.router)
api_router.include_router(voice_sessions.router)
api_router.include_router(omnichannel_channels.router)
api_router.include_router(omnichannel_conversations.router)
api_router.include_router(omnichannel_realtime.router)
api_router.include_router(omnichannel_widget.router)
api_router.include_router(omnichannel_webhooks.router)
api_router.include_router(conversations.router)
api_router.include_router(departments.router)
api_router.include_router(teams.router)
api_router.include_router(permissions.router)
api_router.include_router(users.router)
api_router.include_router(roles.router)
