"""add embedded_at to knowledge_documents

Revision ID: a1bc7c084225
Revises: a3c8f1d92e47
Create Date: 2026-06-10 17:02:04.011378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bc7c084225'
down_revision: Union[str, Sequence[str], None] = 'a3c8f1d92e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'embedded_at')
    # ### end Alembic commands ###
